In [1]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

In [2]:
df=pd.read_csv("C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\dataset 14-20.csv")

In [3]:
df

,Title,Director,Cast,Genre,Unnamed: 4
0,Mr Joe B. Carvalho,Samir Tiwari,"Arshad Warsi, Soha Ali Khan, Javed Jaffrey, Vi...",Comedy,NaN
1,Sholay 3D,Ramesh Sippy,"Dharmendra, Amitabh Bachchan, Hema Malini, Jay...",Action/Adventure,NaN
2,Dedh Ishqiya,Abhishek Chaubey_,"Naseeruddin Shah, Arshad Warsi, Madhuri Dixit,...",Black Comedy/Thriller,NaN
3,Yaariyan,Divya Khosla Kumar,"Himansh Kohli, Shreyas Pardiwalla, Dev Sharma,...",Romance,NaN
4,Karle Pyaar Kade,Rajesh Pandey,"Shiv Darshan, Hasleen Kaur",Romance,NaN
...,...,...,...,...,...
500,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy,NaN
501,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller,NaN
502,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama,NaN
503,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller,NaN
504,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama,NaN

In [4]:
df_hin = df[['Title','Director','Cast','Genre']]

In [5]:
df_hin

,Title,Director,Cast,Genre
0,Mr Joe B. Carvalho,Samir Tiwari,"Arshad Warsi, Soha Ali Khan, Javed Jaffrey, Vi...",Comedy
1,Sholay 3D,Ramesh Sippy,"Dharmendra, Amitabh Bachchan, Hema Malini, Jay...",Action/Adventure
2,Dedh Ishqiya,Abhishek Chaubey_,"Naseeruddin Shah, Arshad Warsi, Madhuri Dixit,...",Black Comedy/Thriller
3,Yaariyan,Divya Khosla Kumar,"Himansh Kohli, Shreyas Pardiwalla, Dev Sharma,...",Romance
4,Karle Pyaar Kade,Rajesh Pandey,"Shiv Darshan, Hasleen Kaur",Romance
...,...,...,...,...
500,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy
501,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller
502,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama
503,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller
504,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama

In [6]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (1.7.7)
Requirement already satisfied: requests in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from tmdbv3api) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (2022.12.7)

[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '28a4d63a51fd003a26ae5b50b3d0832d'

In [8]:
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [9]:
df_hin

,Title,Director,Cast,Genre
0,Mr Joe B. Carvalho,Samir Tiwari,"Arshad Warsi, Soha Ali Khan, Javed Jaffrey, Vi...",Comedy
1,Sholay 3D,Ramesh Sippy,"Dharmendra, Amitabh Bachchan, Hema Malini, Jay...",Action/Adventure
2,Dedh Ishqiya,Abhishek Chaubey_,"Naseeruddin Shah, Arshad Warsi, Madhuri Dixit,...",Black Comedy/Thriller
3,Yaariyan,Divya Khosla Kumar,"Himansh Kohli, Shreyas Pardiwalla, Dev Sharma,...",Romance
4,Karle Pyaar Kade,Rajesh Pandey,"Shiv Darshan, Hasleen Kaur",Romance
...,...,...,...,...
500,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy
501,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller
502,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama
503,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller
504,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama

In [10]:
df_hin = df_hin.rename(columns={'Director':'director_name'})

In [11]:
df_hin = df_hin.rename(columns={'Genre':'genres'})

In [12]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [13]:
df_hin['actor_1_name'] = df_hin['Cast'].map(lambda x: get_actor1(str(x)))

In [14]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [15]:
df_hin['actor_2_name'] = df_hin['Cast'].map(lambda x: get_actor2(str(x)))

In [16]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [17]:
df_hin['actor_3_name'] = df_hin['Cast'].map(lambda x: get_actor3(str(x)))

In [18]:
df_hin

,Title,director_name,Cast,genres,actor_1_name,actor_2_name,actor_3_name
0,Mr Joe B. Carvalho,Samir Tiwari,"Arshad Warsi, Soha Ali Khan, Javed Jaffrey, Vi...",Comedy,Arshad Warsi,Soha Ali Khan,Javed Jaffrey
1,Sholay 3D,Ramesh Sippy,"Dharmendra, Amitabh Bachchan, Hema Malini, Jay...",Action/Adventure,Dharmendra,Amitabh Bachchan,Hema Malini
2,Dedh Ishqiya,Abhishek Chaubey_,"Naseeruddin Shah, Arshad Warsi, Madhuri Dixit,...",Black Comedy/Thriller,Naseeruddin Shah,Arshad Warsi,Madhuri Dixit
3,Yaariyan,Divya Khosla Kumar,"Himansh Kohli, Shreyas Pardiwalla, Dev Sharma,...",Romance,Himansh Kohli,Shreyas Pardiwalla,Dev Sharma
4,Karle Pyaar Kade,Rajesh Pandey,"Shiv Darshan, Hasleen Kaur",Romance,Shiv Darshan,Hasleen Kaur,NaN
...,...,...,...,...,...,...,...
500,Fukrey Returns,Mrighdeep Singh Lamba,"Pulkit Samrat, Priya Anand, Ali Fazal, Varun S...",Comedy,Pulkit Samrat,Priya Anand,Ali Fazal
501,Game Over,Paresh Vinodray Savani,"Rajesh Sharma, Yashpal Sharma, Gurleen Chopra",Suspense/thriller,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra
502,Sallu Ki Shaadi,Mohammad Israr Ansari,"Zeenat Aman, Kiran Kumar, Asrani, Kshayp, Arsh...",Comedy drama,Zeenat Aman,Kiran Kumar,Asrani
503,Monsoon Shootout,Amit Kumar,"Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...",Crime/thriller,Nawazuddin Siddiqui,Vijay Varma & Tannishtha Chatterjee,NaN
504,Tiger Zinda Hai,Ali Abbas Zafar,Salman Khan & Katrina Kaif,Action/drama,Salman Khan & Katrina Kaif,NaN,NaN

In [19]:
df_hin = df_hin.rename(columns={'Title':'movie_title'})

In [20]:
new_df = df_hin.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [21]:
new_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Samir Tiwari,Arshad Warsi,Soha Ali Khan,Javed Jaffrey,Comedy,Mr Joe B. Carvalho
1,Ramesh Sippy,Dharmendra,Amitabh Bachchan,Hema Malini,Action/Adventure,Sholay 3D
2,Abhishek Chaubey_,Naseeruddin Shah,Arshad Warsi,Madhuri Dixit,Black Comedy/Thriller,Dedh Ishqiya
3,Divya Khosla Kumar,Himansh Kohli,Shreyas Pardiwalla,Dev Sharma,Romance,Yaariyan
4,Rajesh Pandey,Shiv Darshan,Hasleen Kaur,NaN,Romance,Karle Pyaar Kade
...,...,...,...,...,...,...
500,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy,Fukrey Returns
501,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Suspense/thriller,Game Over
502,Mohammad Israr Ansari,Zeenat Aman,Kiran Kumar,Asrani,Comedy drama,Sallu Ki Shaadi
503,Amit Kumar,Nawazuddin Siddiqui,Vijay Varma & Tannishtha Chatterjee,NaN,Crime/thriller,Monsoon Shootout
504,Ali Abbas Zafar,Salman Khan & Katrina Kaif,NaN,NaN,Action/drama,Tiger Zinda Hai

In [22]:
print(new_df.dtypes)

director_name    object
actor_1_name     object
actor_2_name     object
actor_3_name     object
genres           object
movie_title      object
dtype: object

In [23]:
for column in ['actor_1_name', 'actor_2_name', 'actor_3_name', 'director_name', 'genres']:
    for i in range(len(new_df)):
        new_df.at[i, column] = str(new_df.at[i, column])

new_df['comb'] = new_df['actor_1_name'] + ' ' + new_df['actor_2_name'] + ' ' + new_df['actor_3_name'] + ' ' + new_df['director_name'] + ' ' + new_df['genres']

In [24]:
print(new_df.dtypes)

director_name    object
actor_1_name     object
actor_2_name     object
actor_3_name     object
genres           object
movie_title      object
comb             object
dtype: object

In [25]:
new_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      5
comb             0
dtype: int64

In [26]:
new_df22 = new_df.dropna(how='any')

In [27]:
new_df22.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [28]:
new_df22['movie_title'] = new_df22['movie_title'].str.lower()

C:\Users\Ankan Dutta\AppData\Local\Temp\ipykernel_28548\2732328091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df22['movie_title'] = new_df22['movie_title'].str.lower()

In [29]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Samir Tiwari,Arshad Warsi,Soha Ali Khan,Javed Jaffrey,Comedy,mr joe b. carvalho,Arshad Warsi Soha Ali Khan Javed Jaffrey Samir...
1,Ramesh Sippy,Dharmendra,Amitabh Bachchan,Hema Malini,Action/Adventure,sholay 3d,Dharmendra Amitabh Bachchan Hema Malini Ramesh...
2,Abhishek Chaubey_,Naseeruddin Shah,Arshad Warsi,Madhuri Dixit,Black Comedy/Thriller,dedh ishqiya,Naseeruddin Shah Arshad Warsi Madhuri Dixit Ab...
3,Divya Khosla Kumar,Himansh Kohli,Shreyas Pardiwalla,Dev Sharma,Romance,yaariyan,Himansh Kohli Shreyas Pardiwalla Dev Sharma Di...
4,Rajesh Pandey,Shiv Darshan,Hasleen Kaur,nan,Romance,karle pyaar kade,Shiv Darshan Hasleen Kaur nan Rajesh Pandey Ro...
...,...,...,...,...,...,...,...
500,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy,fukrey returns,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
501,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Suspense/thriller,game over,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
502,Mohammad Israr Ansari,Zeenat Aman,Kiran Kumar,Asrani,Comedy drama,sallu ki shaadi,Zeenat Aman Kiran Kumar Asrani Mohammad Israr ...
503,Amit Kumar,Nawazuddin Siddiqui,Vijay Varma & Tannishtha Chatterjee,nan,Crime/thriller,monsoon shootout,Nawazuddin Siddiqui Vijay Varma & Tannishtha C...
504,Ali Abbas Zafar,Salman Khan & Katrina Kaif,nan,nan,Action/drama,tiger zinda hai,Salman Khan & Katrina Kaif nan nan Ali Abbas Z...

In [30]:
old_df = pd.read_csv('C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\main_data.csv')

In [31]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
8512,Dharan Mandarayar,Sonali Kulkarni,Amardeep Jha,Shameem Shaikh,Drama,white rainbow,Sonali Kulkarni Amardeep Jha Shameem Shaikh Dh...
8513,Mohit Suri,Kangana Ranaut,Shiney Ahuja,NaN,"Drama, Romance, Social",woh lamhe...,Kangana Ranaut Shiney Ahuja nan Mohit Suri Dra...
8514,Nasseruddin Shah,Ayesha Takia,Konkona Sen Sharma,Paresh Rawal,Drama,yun hota toh kya hota,Ayesha Takia Konkona Sen Sharma Paresh Rawal N...
8515,Sanjay Gupta,Sanjay Dutt,John Abraham,Lara Dutta,Thriller,zinda,Sanjay Dutt John Abraham Lara Dutta Sanjay Gup...
8516,Tanuja Chandra,Sushmita Sen,Shiney Ahuja,NaN,Drama,zindaggi rocks,Sushmita Sen Shiney Ahuja nan Tanuja Chandra D...

In [32]:
final_df = old_df.append(new_df22,ignore_index=True)

C:\Users\Ankan Dutta\AppData\Local\Temp\ipykernel_28548\1166909226.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = old_df.append(new_df22,ignore_index=True)

In [33]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakensÂ ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
9012,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy,fukrey returns,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
9013,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Suspense/thriller,game over,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
9014,Mohammad Israr Ansari,Zeenat Aman,Kiran Kumar,Asrani,Comedy drama,sallu ki shaadi,Zeenat Aman Kiran Kumar Asrani Mohammad Israr ...
9015,Amit Kumar,Nawazuddin Siddiqui,Vijay Varma & Tannishtha Chatterjee,nan,Crime/thriller,monsoon shootout,Nawazuddin Siddiqui Vijay Varma & Tannishtha C...
9016,Ali Abbas Zafar,Salman Khan & Katrina Kaif,nan,nan,Action/drama,tiger zinda hai,Salman Khan & Katrina Kaif nan nan Ali Abbas Z...

In [34]:
final_df.to_csv('C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\main_data.csv',index=False)