In [19]:
import pandas as pd
import numpy as np
import requests
import bs4 as bs
import urllib.request

In [20]:
df=pd.read_csv("C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\dataset.csv")

In [21]:
df

,Title,Director,Cast
0,1921,Vikram Bhatt,"Zareen Khan, Karan Kundra, Tobby Hinston,Sonia..."
1,Kaalakaandi,Akshat Verma,"Saif Ali Khan, Isha Talwar, Shenaz Treasury, A..."
2,Mukkabaaz,Anurag Kashyap,"Vineet Kumar Singh, Zoya Hussain, Ravi Kishan,..."
3,PhirSe..,Kunal Kohli,"Jennifer Winget, Kunal Kohli, Rajit Kapur"
4,My Birthday Song,Samir Soni,"Sanjay Suri, Nora Fatehi, Pitobash"
...,...,...,...
331,Omprakash Zindabad,Ranjeet Gupta,"Kulbhushan Kharbanda , Jagdeep , Shweta Bhardw..."
332,Unpaused,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...","Gulshan Devaiah , Sumeet Vyas , Saiyami Kher ,..."
333,AK vs AK,Vikramaditya Motwane,"Anil Kapoor , Anurag Kashyap"
334,Coolie No. 1,David Dhawan,"Varun Dhawan , Sara Ali Khan"
335,Shakeela,Indrajit Lankesh,"Richa Chadda , Pankaj Tripathi , Rajeev Pillai"

In [22]:
df_hin = df[['Title','Director','Cast']]

In [23]:
df_hin

,Title,Director,Cast
0,1921,Vikram Bhatt,"Zareen Khan, Karan Kundra, Tobby Hinston,Sonia..."
1,Kaalakaandi,Akshat Verma,"Saif Ali Khan, Isha Talwar, Shenaz Treasury, A..."
2,Mukkabaaz,Anurag Kashyap,"Vineet Kumar Singh, Zoya Hussain, Ravi Kishan,..."
3,PhirSe..,Kunal Kohli,"Jennifer Winget, Kunal Kohli, Rajit Kapur"
4,My Birthday Song,Samir Soni,"Sanjay Suri, Nora Fatehi, Pitobash"
...,...,...,...
331,Omprakash Zindabad,Ranjeet Gupta,"Kulbhushan Kharbanda , Jagdeep , Shweta Bhardw..."
332,Unpaused,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...","Gulshan Devaiah , Sumeet Vyas , Saiyami Kher ,..."
333,AK vs AK,Vikramaditya Motwane,"Anil Kapoor , Anurag Kashyap"
334,Coolie No. 1,David Dhawan,"Varun Dhawan , Sara Ali Khan"
335,Shakeela,Indrajit Lankesh,"Richa Chadda , Pankaj Tripathi , Rajeev Pillai"

In [24]:
!pip install tmdbv3api

Requirement already satisfied: tmdbv3api in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (1.7.7)
Requirement already satisfied: requests in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from tmdbv3api) (2.28.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ankan dutta\appdata\local\programs\python\python311\lib\site-packages (from requests->tmdbv3api) (2022.12.7)

[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
from tmdbv3api import TMDb
import json
import requests
tmdb = TMDb()
tmdb.api_key = '28a4d63a51fd003a26ae5b50b3d0832d'

In [26]:
from tmdbv3api import Movie
tmdb_movie = Movie() 
def get_genre(x):
    genres = []
    result = tmdb_movie.search(x)
    if not result:
      return np.NaN
    else:
      movie_id = result[0].id
      response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
      data_json = response.json()
      if data_json['genres']:
          genre_str = " " 
          for i in range(0,len(data_json['genres'])):
              genres.append(data_json['genres'][i]['name'])
          return genre_str.join(genres)
      else:
          return np.NaN

In [27]:
df_hin['genres'] = df_hin['Title'].map(lambda x: get_genre(str(x)))

In [28]:
df_hin

,Title,Director,Cast,genres
0,1921,Vikram Bhatt,"Zareen Khan, Karan Kundra, Tobby Hinston,Sonia...",History Drama
1,Kaalakaandi,Akshat Verma,"Saif Ali Khan, Isha Talwar, Shenaz Treasury, A...",Comedy Thriller Drama
2,Mukkabaaz,Anurag Kashyap,"Vineet Kumar Singh, Zoya Hussain, Ravi Kishan,...",Drama
3,PhirSe..,Kunal Kohli,"Jennifer Winget, Kunal Kohli, Rajit Kapur",NaN
4,My Birthday Song,Samir Soni,"Sanjay Suri, Nora Fatehi, Pitobash",Thriller
...,...,...,...,...
331,Omprakash Zindabad,Ranjeet Gupta,"Kulbhushan Kharbanda , Jagdeep , Shweta Bhardw...",NaN
332,Unpaused,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...","Gulshan Devaiah , Sumeet Vyas , Saiyami Kher ,...",Comedy Drama
333,AK vs AK,Vikramaditya Motwane,"Anil Kapoor , Anurag Kashyap",Comedy Action Drama Crime
334,Coolie No. 1,David Dhawan,"Varun Dhawan , Sara Ali Khan",Comedy Drama
335,Shakeela,Indrajit Lankesh,"Richa Chadda , Pankaj Tripathi , Rajeev Pillai",Drama Romance

In [29]:
df_hin = df_hin.rename(columns={'Director':'director_name'})

In [30]:
def get_actor1(x):
    return ((x.split("screenplay); ")[-1]).split(", ")[0])

In [31]:
df_hin['actor_1_name'] = df_hin['Cast'].map(lambda x: get_actor1(str(x)))

In [32]:
def get_actor2(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 2:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[1])

In [33]:
df_hin['actor_2_name'] = df_hin['Cast'].map(lambda x: get_actor2(str(x)))

In [34]:
def get_actor3(x):
    if len((x.split("screenplay); ")[-1]).split(", ")) < 3:
        return np.NaN
    else:
        return ((x.split("screenplay); ")[-1]).split(", ")[2])

In [35]:
df_hin['actor_3_name'] = df_hin['Cast'].map(lambda x: get_actor3(str(x)))

In [36]:
df_hin

,Title,director_name,Cast,genres,actor_1_name,actor_2_name,actor_3_name
0,1921,Vikram Bhatt,"Zareen Khan, Karan Kundra, Tobby Hinston,Sonia...",History Drama,Zareen Khan,Karan Kundra,"Tobby Hinston,Sonia Armstrong"
1,Kaalakaandi,Akshat Verma,"Saif Ali Khan, Isha Talwar, Shenaz Treasury, A...",Comedy Thriller Drama,Saif Ali Khan,Isha Talwar,Shenaz Treasury
2,Mukkabaaz,Anurag Kashyap,"Vineet Kumar Singh, Zoya Hussain, Ravi Kishan,...",Drama,Vineet Kumar Singh,Zoya Hussain,Ravi Kishan
3,PhirSe..,Kunal Kohli,"Jennifer Winget, Kunal Kohli, Rajit Kapur",NaN,Jennifer Winget,Kunal Kohli,Rajit Kapur
4,My Birthday Song,Samir Soni,"Sanjay Suri, Nora Fatehi, Pitobash",Thriller,Sanjay Suri,Nora Fatehi,Pitobash
...,...,...,...,...,...,...,...
331,Omprakash Zindabad,Ranjeet Gupta,"Kulbhushan Kharbanda , Jagdeep , Shweta Bhardw...",NaN,Kulbhushan Kharbanda,Jagdeep,Shweta Bhardwaj
332,Unpaused,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...","Gulshan Devaiah , Sumeet Vyas , Saiyami Kher ,...",Comedy Drama,Gulshan Devaiah,Sumeet Vyas,Saiyami Kher
333,AK vs AK,Vikramaditya Motwane,"Anil Kapoor , Anurag Kashyap",Comedy Action Drama Crime,Anil Kapoor,Anurag Kashyap,NaN
334,Coolie No. 1,David Dhawan,"Varun Dhawan , Sara Ali Khan",Comedy Drama,Varun Dhawan,Sara Ali Khan,NaN
335,Shakeela,Indrajit Lankesh,"Richa Chadda , Pankaj Tripathi , Rajeev Pillai",Drama Romance,Richa Chadda,Pankaj Tripathi,Rajeev Pillai

In [37]:
df_hin = df_hin.rename(columns={'Title':'movie_title'})

In [38]:
new_df = df_hin.loc[:,['director_name','actor_1_name','actor_2_name','actor_3_name','genres','movie_title']]

In [39]:
new_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title
0,Vikram Bhatt,Zareen Khan,Karan Kundra,"Tobby Hinston,Sonia Armstrong",History Drama,1921
1,Akshat Verma,Saif Ali Khan,Isha Talwar,Shenaz Treasury,Comedy Thriller Drama,Kaalakaandi
2,Anurag Kashyap,Vineet Kumar Singh,Zoya Hussain,Ravi Kishan,Drama,Mukkabaaz
3,Kunal Kohli,Jennifer Winget,Kunal Kohli,Rajit Kapur,NaN,PhirSe..
4,Samir Soni,Sanjay Suri,Nora Fatehi,Pitobash,Thriller,My Birthday Song
...,...,...,...,...,...,...
331,Ranjeet Gupta,Kulbhushan Kharbanda,Jagdeep,Shweta Bhardwaj,NaN,Omprakash Zindabad
332,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...",Gulshan Devaiah,Sumeet Vyas,Saiyami Kher,Comedy Drama,Unpaused
333,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,NaN,Comedy Action Drama Crime,AK vs AK
334,David Dhawan,Varun Dhawan,Sara Ali Khan,NaN,Comedy Drama,Coolie No. 1
335,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,Drama Romance,Shakeela

In [40]:
print(new_df.dtypes)

director_name    object
actor_1_name     object
actor_2_name     object
actor_3_name     object
genres           object
movie_title      object
dtype: object

In [41]:
for column in ['actor_1_name', 'actor_2_name', 'actor_3_name', 'director_name', 'genres']:
    for i in range(len(new_df)):
        new_df.at[i, column] = str(new_df.at[i, column])

new_df['comb'] = new_df['actor_1_name'] + ' ' + new_df['actor_2_name'] + ' ' + new_df['actor_3_name'] + ' ' + new_df['director_name'] + ' ' + new_df['genres']

In [42]:
new_df.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      4
comb             0
dtype: int64

In [43]:
new_df22 = new_df.dropna(how='any')

In [44]:
new_df22.isna().sum()

director_name    0
actor_1_name     0
actor_2_name     0
actor_3_name     0
genres           0
movie_title      0
comb             0
dtype: int64

In [45]:
new_df22['movie_title'] = new_df22['movie_title'].str.lower()

C:\Users\Ankan Dutta\AppData\Local\Temp\ipykernel_23236\2732328091.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df22['movie_title'] = new_df22['movie_title'].str.lower()

In [46]:
new_df22

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,Vikram Bhatt,Zareen Khan,Karan Kundra,"Tobby Hinston,Sonia Armstrong",History Drama,1921,"Zareen Khan Karan Kundra Tobby Hinston,Sonia A..."
1,Akshat Verma,Saif Ali Khan,Isha Talwar,Shenaz Treasury,Comedy Thriller Drama,kaalakaandi,Saif Ali Khan Isha Talwar Shenaz Treasury Aksh...
2,Anurag Kashyap,Vineet Kumar Singh,Zoya Hussain,Ravi Kishan,Drama,mukkabaaz,Vineet Kumar Singh Zoya Hussain Ravi Kishan An...
3,Kunal Kohli,Jennifer Winget,Kunal Kohli,Rajit Kapur,nan,phirse..,Jennifer Winget Kunal Kohli Rajit Kapur Kunal ...
4,Samir Soni,Sanjay Suri,Nora Fatehi,Pitobash,Thriller,my birthday song,Sanjay Suri Nora Fatehi Pitobash Samir Soni Th...
...,...,...,...,...,...,...,...
331,Ranjeet Gupta,Kulbhushan Kharbanda,Jagdeep,Shweta Bhardwaj,nan,omprakash zindabad,Kulbhushan Kharbanda Jagdeep Shweta Bhardwaj...
332,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...",Gulshan Devaiah,Sumeet Vyas,Saiyami Kher,Comedy Drama,unpaused,Gulshan Devaiah Sumeet Vyas Saiyami Kher Ra...
333,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,nan,Comedy Action Drama Crime,ak vs ak,Anil Kapoor Anurag Kashyap nan Vikramaditya M...
334,David Dhawan,Varun Dhawan,Sara Ali Khan,nan,Comedy Drama,coolie no. 1,Varun Dhawan Sara Ali Khan nan David Dhawan C...
335,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,Drama Romance,shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai I...

In [47]:
old_df = pd.read_csv('C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\main_data.csv')

In [48]:
old_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
9012,Mrighdeep Singh Lamba,Pulkit Samrat,Priya Anand,Ali Fazal,Comedy,fukrey returns,Pulkit Samrat Priya Anand Ali Fazal Mrighdeep ...
9013,Paresh Vinodray Savani,Rajesh Sharma,Yashpal Sharma,Gurleen Chopra,Suspense/thriller,game over,Rajesh Sharma Yashpal Sharma Gurleen Chopra Pa...
9014,Mohammad Israr Ansari,Zeenat Aman,Kiran Kumar,Asrani,Comedy drama,sallu ki shaadi,Zeenat Aman Kiran Kumar Asrani Mohammad Israr ...
9015,Amit Kumar,Nawazuddin Siddiqui,Vijay Varma & Tannishtha Chatterjee,NaN,Crime/thriller,monsoon shootout,Nawazuddin Siddiqui Vijay Varma & Tannishtha C...
9016,Ali Abbas Zafar,Salman Khan & Katrina Kaif,NaN,NaN,Action/drama,tiger zinda hai,Salman Khan & Katrina Kaif nan nan Ali Abbas Z...

In [49]:
final_df = old_df.append(new_df22,ignore_index=True)

C:\Users\Ankan Dutta\AppData\Local\Temp\ipykernel_23236\1166909226.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final_df = old_df.append(new_df22,ignore_index=True)

In [50]:
final_df

,director_name,actor_1_name,actor_2_name,actor_3_name,genres,movie_title,comb
0,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,Action Adventure Fantasy Sci-Fi,avatar,CCH Pounder Joel David Moore Wes Studi James C...
1,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,Action Adventure Fantasy,pirates of the caribbean: at world's end,Johnny Depp Orlando Bloom Jack Davenport Gore ...
2,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,Action Adventure Thriller,spectre,Christoph Waltz Rory Kinnear Stephanie Sigman ...
3,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,Action Thriller,the dark knight rises,Tom Hardy Christian Bale Joseph Gordon-Levitt ...
4,Doug Walker,Doug Walker,Rob Walker,unknown,Documentary,star wars: episode vii - the force awakens ...,Doug Walker Rob Walker unknown Doug Walker Doc...
...,...,...,...,...,...,...,...
9344,Ranjeet Gupta,Kulbhushan Kharbanda,Jagdeep,Shweta Bhardwaj,nan,omprakash zindabad,Kulbhushan Kharbanda Jagdeep Shweta Bhardwaj...
9345,"Raj & D.K Nitya Mehra Nikkhil Advani , Tannish...",Gulshan Devaiah,Sumeet Vyas,Saiyami Kher,Comedy Drama,unpaused,Gulshan Devaiah Sumeet Vyas Saiyami Kher Ra...
9346,Vikramaditya Motwane,Anil Kapoor,Anurag Kashyap,nan,Comedy Action Drama Crime,ak vs ak,Anil Kapoor Anurag Kashyap nan Vikramaditya M...
9347,David Dhawan,Varun Dhawan,Sara Ali Khan,nan,Comedy Drama,coolie no. 1,Varun Dhawan Sara Ali Khan nan David Dhawan C...
9348,Indrajit Lankesh,Richa Chadda,Pankaj Tripathi,Rajeev Pillai,Drama Romance,shakeela,Richa Chadda Pankaj Tripathi Rajeev Pillai I...

In [51]:
final_df.to_csv('C:\\Users\\Ankan Dutta\\Desktop\\DTI\\datasets\\main_data.csv',index=False)